[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  name = "github.com/gardener/gardener"
  branch = "master"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "github.com/rakyll/statik"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
